### PR TITLE
fix: add missing dependencies

### PR DESCRIPTION
**Pull request by PascalinDe**

### CODE REVIEW

**Review by lanterno — APPROVED** [review]
LGTM

**Comment by lanterno** [comment]
@PascalinDe for typescript, the package manager introduces lock files. I believe they should be pushed/git-tracked as well. 
Otherwise, the manager won't recognize the updates completely. However, I think it's still nice to build them from within docker.

**Review by pierluca — CHANGES_REQUESTED** [review]
I agree with @lanterno. You need to commit the package-lock.json as well.

**Comment by PascalinDe** [comment]
added package-lock.json files as generated in Docker environment

naturally, that also changed some other versions...

**Review by lanterno — APPROVED** [review]

**Review by pierluca — APPROVED** [review]
LGTM

**Pull request merged**
