### PR TITLE
feat: dockerized deployment

### PR DESCRIPTION
**Pull request by PascalinDe**
includes all the relevant files for the new dockerized deployment, including a helper script to set up/tear down a development environment

### CODE REVIEW

**Review by jbsv — APPROVED** [review]
Looks good to me! Thanks

**Comment by PascalinDe** [comment]
I'll have a look why the test is broken, it seems like there's some problem with the DELA version...

**Comment by ineiti** [comment]
> I'll have a look why the test is broken, it seems like there's some problem with the DELA version...

Yes, it relies on the latest dela with the new protocol names.

**Comment by PascalinDe** [comment]
since the reason the test is failing is not related to this PR, I think it can be merged

@jbsv I'll let you hit the merge button

**Comment by ineiti** [comment]
> since the reason the test is failing is not related to this PR, I think it can be merged
> 
> @jbsv I'll let you hit the merge button

Sorry, no, please don't merge. If you do, you put the dedis/d-voting repository in an unstable state. We first need to merge the dela-PR before this PR can be merged.

**Comment by PascalinDe** [comment]
> > since the reason the test is failing is not related to this PR, I think it can be merged
> > @jbsv I'll let you hit the merge button
> 
> Sorry, no, please don't merge. If you do, you put the dedis/d-voting repository in an unstable state. We first need to merge the dela-PR before this PR can be merged.

maybe I missed something, but how would this PR put the repository in an unstable state? it's only for a merge onto our branch (`c4dt-main`) and only contains some documentation, the code for the Docker images and a script - none of which are executed automatically (the Docker images are only build on the `main` branch by the CI)

also the CI for the tests is already broken on this branch

**Pull request closed without merging**
